### ISSUE TITLE
Error when starting ros2ez

### ISSUE THREAD

**Issue by Dkoutrintzes** [gstavrinos/ros-ez#8]
Sometimes when I ran the command ros2ez it returns the following error. 

> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/dist-packages/docker/api/client.py", line 268, in _raise_for_status
> 	response.raise_for_status()
>   File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 1021, in raise_for_status
> 	raise HTTPError(http_error_msg, response=self)
> requests.exceptions.HTTPError: 409 Client Error: Conflict for url: http+docker://localhost/v1.42/images/rocker:os_detect_ros2_ez_latest?force=False&noprune=False
> The above exception was the direct cause of the following exception:
> Traceback (most recent call last):
>   File "/usr/local/bin/rocker", line 8, in <module>
> 	sys.exit(main())
>   File "/usr/local/lib/python3.10/dist-packages/rocker/cli.py", line 66, in main
> 	dig = DockerImageGenerator(active_extensions, args_dict, base_image)
>   File "/usr/local/lib/python3.10/dist-packages/rocker/core.py", line 210, in __init__
> 	self.dockerfile = generate_dockerfile(active_extensions, self.cliargs, base_image)
>   File "/usr/local/lib/python3.10/dist-packages/rocker/core.py", line 344, in generate_dockerfile
> 	dockerfile_str += el.get_preamble(args_dict) + '\n'
>   File "/usr/local/lib/python3.10/dist-packages/rocker/nvidia_extension.py", line 118, in get_preamble
> 	return em.expand(preamble, self.get_environment_subs(cliargs))
>   File "/usr/local/lib/python3.10/dist-packages/rocker/nvidia_extension.py", line 98, in get_environment_subs
> 	detected_os = detect_os(cliargs['base_image'], print, nocache=cliargs.get('nocache', False))
>   File "/usr/local/lib/python3.10/dist-packages/rocker/os_detector.py", line 81, in detect_os
> 	client.remove_image(image=tag_name)
>   File "/usr/local/lib/python3.10/dist-packages/docker/utils/decorators.py", line 19, in wrapped
> 	return f(self, resource_id, *args, **kwargs)
>   File "/usr/local/lib/python3.10/dist-packages/docker/api/image.py", line 514, in remove_image
> 	return self._result(res, True)
>   File "/usr/local/lib/python3.10/dist-packages/docker/api/client.py", line 274, in _result
> 	self._raise_for_status(response)
>   File "/usr/local/lib/python3.10/dist-packages/docker/api/client.py", line 270, in _raise_for_status
> 	raise create_api_error_from_http_exception(e) from e
>   File "/usr/local/lib/python3.10/dist-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
> 	raise cls(e, response=response, explanation=explanation) from e
> docker.errors.APIError: 409 Client Error for http+docker://localhost/v1.42/images/rocker:os_detect_ros2_ez_latest?force=False&noprune=False: Conflict ("conflict: unable to remove repository reference "rocker:os_detect_ros2_ez_latest" (must force) - container b08d20fc871f is using its referenced image e39473376116")
> touch: missing file operand
> Try 'touch --help' for more information.
> xauth:  file nmerge does not exist
> Using authority file nmerge
> xauth: (stdin):1:  unknown command "ffff"
> xauth: (stdin):2:  unknown command "ffff"
> Executing:
> sudo  env  /bin/bash
> 
> 

This happens mostly when I try to open multiple terminals and open ros to all of them at once. I ran a docker image list after the error and the images were the following. 

> koutris@koutris-System:~/Desktop$ sudo docker images
> REPOSITORY  	TAG                       	IMAGE ID   	CREATED      	SIZE
> rocker      	os_detect_ros2_ez_latest  	23f7537298cd   12 minutes ago   4.78GB
> <none>      	<none>                    	de3d11a6d367   12 minutes ago   4.78GB
> <none>      	<none>                    	12ee62987052   6 days ago   	4.77GB
> <none>      	<none>                    	65080f65361b   6 days ago   	4.77GB
> <none>      	<none>                    	845c9330add8   6 days ago   	252MB
> ros2_ez     	latest                    	3368a07606b9   6 days ago   	4.77GB
> <none>      	<none>                    	3c2e7ac1272e   6 days ago   	4.77GB
> <none>      	<none>                    	b33916cace85   6 days ago   	4.77GB
> <none>      	<none>                    	666b34957dac   6 days ago   	4.77GB
> <none>      	<none>                    	282ec15ba8f1   6 days ago   	4.77GB
> <none>      	<none>                    	91a8896f6b98   6 days ago   	4.77GB
> snyk/snyk   	<none>                    	4db3fcadc7e4   2 months ago 	213MB
> nvidia/opengl   1.0-glvnd-devel-ubuntu18.04   9d806b36b807   9 months ago 	413MB
> hello-world 	latest                    	feb5d9fea6a5   17 months ago	13.3kB
> python      	3-slim-stretch            	7691d3cb6cbc   3 years ago  	155MB
> 

after I run a docker image prune only the following remain and the error was fixed.

> 
> koutris@koutris-System:~/Desktop$ sudo docker images
> REPOSITORY  	TAG                       	IMAGE ID   	CREATED      	SIZE
> rocker      	os_detect_ros2_ez_latest  	23f7537298cd   14 minutes ago   4.78GB
> <none>      	<none>                    	de3d11a6d367   14 minutes ago   4.78GB
> <none>      	<none>                    	65080f65361b   6 days ago   	4.77GB
> ros2_ez     	latest                    	3368a07606b9   6 days ago   	4.77GB
> nvidia/opengl   1.0-glvnd-devel-ubuntu18.04   9d806b36b807   9 months ago 	413MB
> hello-world 	latest                    	feb5d9fea6a5   17 months ago	13.3kB
> python      	3-slim-stretch            	7691d3cb6cbc   3 years ago  	155MB

I manage to recreate the error by running the bash ros2_installer.bash command when I was outside the folder. 

`bash ros-ez/ros2_installer.bash`
 
ROS 2, ros-ez version 1.0.0, Ubuntu LTS 22.04

**Comment by gstavrinos** [comment]
Thanks for the report. The concurrency problem is a known one, and a new milestone for version `v1.2.0` has been set, and will be fixed asap.

I am not really sure that the way you recreated the error is the same with the concurrency one. The location handling was a problem that was fixed in `v1.1.0` though.

I would recommend switching to `v1.1.0` with some caveats regarding permissions. A major difference between `v1.0.0` and `v1.1.0` is permissions handling, so you will most probably encounter owner/permissions issues that should be fixed if you **ch**ange **own**er.

For now, either in `v1.0.0` or `v1.1.0`, please refrain from running concurrent ros*ez commands, but wait for the compilation to complete before running a new command instead.

Please keep me updated, and look forward to `v1.2.0`. Also, keep in mind that `v1.2.0` should not have any breaking changes from `v1.1.0`.
